name: music_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  permission_handler: ^11.2.0
  just_audio: ^0.9.36
  on_audio_query: ^2.9.0
  layout_pro: ^0.0.3
  shimmer_effect: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true